# https://github.com/elastic/elasticsearch-docker
FROM registry.dataos.io/elastic/elasticsearch:5.2.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
